export default {
  CREATE_GROUP: 'CREATE_GROUP',
  UPDATE_GROUP: 'UPDATE_GROUP',
  DELETE_GROUP: 'DELETE_GROUP',
  FETCH_GROUP: 'FETCH_GROUP',

  FETCH_MEMBERS: 'GROUP_FETCH_MEMBERS',
  ADD_MEMBER: 'GROUP_ADD_MEMBER',
  REMOVE_MEMBER: 'GROUP_REMOVE_MEMBER',
}
