export default {
  CREATE_MDS: 'CREATE_MDS',
  UPDATE_MDS: 'UPDATE_MDS',
  DELETE_MDS: 'DELETE_MDS',
  FETCH_MDS: 'FETCH_MDS',

  FETCH_PROTOCOLS: 'FETCH_PROTOCOLS',
  ADD_PROTOCOL: 'ADD_PROTOCOL',
  REMOVE_PROTOCOL: 'REMOVE_PROTOCOL',
}
