export default {
  CREATE_MDS: 'CREATE_MDS',
  UPDATE_MDS: 'UPDATE_MDS',
  DELETE_MDS: 'DELETE_MDS',
  FETCH_MDS: 'FETCH_MDS',
  LIST_MDS: 'LIST_MDS',

  FETCH_PROTOCOLS: 'MDS_FETCH_PROTOCOLS',
  ADD_PROTOCOL: 'MDS_ADD_PROTOCOL',
  REMOVE_PROTOCOL: 'MDS_REMOVE_PROTOCOL',

  SYNCHRONIZE: 'SYNCHRONIZE',
}
