export default {
  CREATE_ORGANIZATION: 'CREATE_ORGANIZATION',
  UPDATE_ORGANIZATION: 'UPDATE_ORGANIZATION',
  DELETE_ORGANIZATION: 'DELETE_ORGANIZATION',
  FETCH_ORGANIZATION: 'FETCH_ORGANIZATION',

  FETCH_GROUPS: 'FETCH_GROUPS',
  ADD_GROUP: 'ADD_GROUP',
  REMOVE_GROUP: 'REMOVE_GROUP',

  FETCH_MEMBERS: 'FETCH_MEMBERS',
  ADD_MEMBER: 'ADD_MEMBER',
  REMOVE_MEMBER: 'REMOVE_MEMBER',

  SWITCH_ACTIVE_ORG: 'SWITCH_ACTIVE_ORG',
}
