export default {
  FETCH_ORGANIZATIONS: 'FETCH_ORGANIZATIONS',
  CREATE_ORGANIZATION: 'CREATE_ORGANIZATION',
  UPDATE_ORGANIZATION: 'UPDATE_ORGANIZATION',
  DELETE_ORGANIZATION: 'DELETE_ORGANIZATION',
  FETCH_ORGANIZATION: 'FETCH_ORGANIZATION',

  FETCH_GROUPS: 'ORGANIZATION_FETCH_GROUPS',
  ADD_GROUP: 'ORGANIZATION_ADD_GROUP',
  REMOVE_GROUP: 'ORGANIZATION_REMOVE_GROUP',

  FETCH_MEMBERS: 'ORGANIZATION_FETCH_MEMBERS',
  ADD_MEMBER: 'ORGANIZATION_ADD_MEMBER',
  REMOVE_MEMBER: 'ORGANIZATION_REMOVE_MEMBER',

  SWITCH_ACTIVE_ORG: 'SWITCH_ACTIVE_ORG',
}
