export default {
  UPDATE_PROTOCOL: 'UPDATE_PROTOCOL',
  FETCH_PROTOCOL: 'FETCH_PROTOCOL',

  FETCH_PROTOCOL_VERSIONS: 'FETCH_PROTOCOL_VERSIONS',

  ADD_TO_ORGANIZATION: 'ADD_PROTOCOL_TO_ORGANIZATION',
  REMOVE_FROM_ORGANIZATION: 'REMOVE_PROTOCOL_FROM_ORGANIZATION',

  FETCH_PROTOCOLS: 'FETCH_PROTOCOLS',
  FETCH_PUBLIC_PROTOCOLS: 'FETCH_PUBLIC_PROTOCOLS',
  FETCH_ORGANIZATION_PROTOCOLS: 'FETCH_ORGANIZATION_PROTOCOLS',
}
